# Generated by Django 4.1.3 on 2022-11-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('symbol', models.CharField(max_length=5)),
            ],
        ),
    ]
